language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION="2.1"
  - SYMFONY_VERSION="2.*"
  - SYMFONY_VERSION="3.0"
  - SYMFONY_VERSION="3.*"
  - SYMFONY_VERSION="4.0"
  - SYMFONY_VERSION="4.*"

before_script:
  - composer self-update
  - composer --version
  - composer require symfony/http-foundation:${SYMFONY_VERSION} --no-update

script: composer install --prefer-dist --no-interaction
